### PR TITLE
Changed how getNumOfAliveNeighbors works

### PR DESCRIPTION
**Pull request by amroessam**
Hi CJ,
I changed the logic, rather than looping through the whole array
I'm only looping -1/+1 cell in each direction unless it's an edge
And only adding the ones that aren't the current cell

### CODE REVIEW

**Comment by amroessam** [comment]
Also sorry for your commas 😝

**Comment by amroessam** [comment]
Lol closed by mistake

**Comment by amroessam** [comment]
Previous method used to traverse the entire array of arrays.
This method only checks 2 < x < 9 elements where x is the element

**Comment by w3cj** [comment]
Thanks for the contribution @amroessam!
I like to keep the code that I wrote during the stream in the file so that when people watch the video in the future, they can see the code I wrote. If you open a new pull request with my existing code commented out and your code above it, I will accept!

**Comment by amroessam** [comment]
Hi CJ redid it, please check your pull requests

**Comment by amroessam** [comment]
@w3cj 2a8cab8302e4f63bebe75d0f891a8dbdce6ac49c

**Pull request closed without merging**
